Website_main_App/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import SignUpView, FarmerSignUpView, CustomerSignUpView, FarmerSignUpView, CustomerSignUpView, LoginView, guest_register_view
from products.views import AddProductView3, FarmerListView

# LoginView, RegisterView

from .views import home_page
from predict.views import predictshow,SalesAjaxView

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    # url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/farmer$', FarmerSignUpView.as_view(), name='farmer_signup'),
    url(r'^signup/customer$', CustomerSignUpView.as_view(), name='customer_signup'),
    url(r'^add-product$', AddProductView3.as_view(), name='add_product'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^my-products$', FarmerListView.as_view(), name='my_product'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include("search.urls", namespace='search')),
    # url(r'^predict/(?P<pk>\d+)/$',predictshow,name='predict'),
    url(r'^predict/$',predictshow,name='predictnoid'),
    url(r'^predict/api/(?P<pk>\d+)/$',SalesAjaxView.as_view(),name='predict-data'),
    url(r'^contact/', include("contact.urls", namespace='contact')),
    url(r'^paypal/', include("paypal.standard.ipn.urls")),
    url(r'^payment/', include("payment.urls", namespace='payment')),

]

if settings.DEBUG:
	urlpatterns =urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns =urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import url

from .views import (
        CartView, 
        ItemCountView,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
	url(r'^$', CartView.as_view(), name='cart'),
    url(r'^count/$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]

products/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        ProductDetailSlugView,
        ProductEditView,
        ProductDeleteView
        # , 
        # ProductDownloadView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit-product$', ProductEditView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete-product$', ProductDeleteView.as_view(), name='delete'),
    # url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
]

products/models.py
import random
from django.db import models
from accounts.models import User
import os
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from Website_main_App.utils import unique_slug_generator

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

class ProductManager(models.Manager):
    # def get_queryset(self):
    #     return ProductQuerySet(self.model, using=self._db)

    # def all(self):
    #     return self.get_queryset().active()

    # def featured(self): #Product.objects.featured() 
    #     return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        lookups = Q(title__icontains=query) | Q(description__icontains=query)
        return self.get_queryset().filter(lookups).distinct()

    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        return self.get_queryset().active()

    # def search(self, query):
    #     return self.get_queryset().active().search(query)


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    # print(instance)
    #print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename, 
            final_filename=final_filename
            )


# Create your models here.
class Product(models.Model):
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    active          = models.BooleanField(default=True)
    price_unit      = models.CharField(max_length=120)
    added_by        = models.ForeignKey(User, default="agromining@gmail.com", verbose_name="Added by", on_delete=models.SET_DEFAULT)
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    timestamp       = models.DateTimeField(auto_now=True)
    availability    = models.BooleanField()


    REQUIRED_FIELDS = ['title', 'availabilty']
    
    # featured        = models.BooleanField(default=False)
    # active          = models.BooleanField(default=True)
    # timestamp       = models.DateTimeField(auto_now_add=True)


    objects = ProductManager()

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug

    # def __unicode__(self):
    #     return self.title

    # @property
    # def name(self):
    #     return self.title

    # def get_downloads(self):
    #     qs = self.productfile_set.all()
    #     return qs

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product) 


# Variation for diffeerent variants of item.
# For example in khukhra there can be broileer and koiler. So need to add two products. Add two variants.
# But here not implemented 
# So if you consider to work with variation following things hould be remembered
# 1) Editing product form will change
# 2) Refer ecommerce2 by cfehome
# 3) def product_post_saved_receiver(sender, instance, created, *args, **kwargs): 
#       will be different(refer ecommerece 2 again)

class Variation(models.Model):
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=120)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    active = models.BooleanField(default=True)
    inventory = models.IntegerField(null=True, blank=True) #refer none == unlimited amount

    def __str__(self):
        return str(self.product)

    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else:
            return self.price

    def get_html_price(self):
        if self.sale_price is not None:
            html_text = "<span class='sale-price'>%s</span> <span class='og-price'>%s</span>" %(self.sale_price, self.price)
        else:
            html_text = "<span class='price'>%s</span>" %(self.price)
        return mark_safe(html_text)

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def add_to_cart(self):
        return "%s?item=%s&qty=1" %(reverse("cart:cart"), self.id)

    def remove_from_cart(self):
        return "%s?item=%s&qty=1&delete=True" %(reverse("cart:cart"), self.id)

    def get_title(self):
        return "%s" %(self.product.title)

def product_post_saved_receiver(sender, instance, created, *args, **kwargs):

    
    product = instance

    Variation.objects.filter(product=product).delete()
    new_var = Variation()
    new_var.product = product
    new_var.title = "Default"
    new_var.price = product.price
    new_var.save()


post_save.connect(product_post_saved_receiver, sender=Product)

products/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView, TemplateView, ListView, DeleteView
from django.utils.http import is_safe_url
from django.shortcuts import render,redirect
from carts.models import Cart
from .models import Product
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import Http404
from .forms import ProductEditForm, ProductEditForm2
from django.views.generic.edit import ModelFormMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin



class MultipleObjectMixin(object):
    def get_object(self, queryset=None, *args, **kwargs):
        slug = self.kwargs.get("slug")
        if slug:
            try:
                obj = self.model.objects.get(slug=slug)
            except self.model.MultipleObjectsReturned:
                obj = self.get_queryset().first()
            except:
                raise Http404
            return obj
        raise Http404

# Create your views here.
# class AddProductView(CreateView): 
# 			template_name = 'products/add.html'

# 			def get(self, request):
# 				form	= ProductEditForm
# 				return render(request, self.template_name, {'form': form})

# 			def post(self, request):
# 				form 	= ProductEditForm(request.POST)

# 				if form.is_valid():
# 					product 	= form.save(commit=False)
# 					product.added_by	= request.user
# 					product.save()
# 					text	= form.cleaned_data['product']
# 					form 	= ProductEditForm
# 					return redirect('/')

# 				args 	= {'form': form, 'text': text}
# 				return render(request, self.template_name, args)

# # class AddProductView2(CreateView):
# class AddProductView2(CreateView):
# 	    	model = Product
#     		form_class = ProductEditForm
#     		template_name = 'products/add.html'
#     		def get_context_data(self, **kwargs):
#     			kwargs['user_type'] = 'customer'
#     			return super().get_context_data(**kwargs)

#     		def form_valid(self, form):
#     			product = form.save()
#     			return redirect('/')

class AddProductView3(CreateView):
    template_name = 'products/add.html'

    def get(self, request):
        form = ProductEditForm2()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ProductEditForm2(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.added_by = request.user 
            product.save()
            form = ProductEditForm2()
            messages.success(request, 'Product Added')
            return redirect('/add-product', message='Product Added')

        args = {'form': form}
        return render(request, self.template_name, args)

class ProductListView(ListView):
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     print(context)
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()

class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context
    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404("Exceptional Error ")
        return instance

# class ProductDetailSlugView(DetailView):
#     queryset = Product.objects.all()
#     template_name = "products/detail.html"

#     def get_context_data(self, *args, **kwargs):
#         context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
#         user_access     = "sdasd"
#         context["user_accessing"] = user_access
#         return context

#     def get_object(self, *args, **kwargs):
#         request = self.request
#         slug = self.kwargs.get('slug')

#         #instance = get_object_or_404(Product, slug=slug, active=True)
#         try:
#             instance = Product.objects.get(slug=slug)
#         except Product.DoesNotExist:
#             raise Http404("Not found..")
#         except Product.MultipleObjectsReturned:
#             qs = Product.objects.filter(slug=slug)
#             instance = qs.first()
#         except:
#             raise Http404("Exceptional Error ")
#         return instance

class FarmerListView(ListView):
    template_name = "products/list.html"
    # added_by = 'abcfarmer@gmail.com'
    # qs      = Product.objects.filter( added_by__email__icontains= added_by )



    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     return context

    def get_queryset(self):
        request = self.request
        added_by = self.request.user
        qs      = Product.objects.filter( added_by__email__icontains= added_by )

        return qs

class ProductEditView(MultipleObjectMixin, UpdateView):
    model = Product
    form_class = ProductEditForm2
    template_name = 'products/edit.html'
  

    def get_context_data(self, *args, **kwargs):
        context = super(ProductEditView, self).get_context_data(*args, **kwargs)
        return context

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'Edit success')
        slug = self.kwargs.get('slug')
        return reverse("products:detail", kwargs={'slug':slug })


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("add_product")
    success_message = "Product was deleted successfully."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ProductDeleteView, self).delete(request, *args, **kwargs)




		
	
			
			

products/templates/products/add.html
{% extends "base.html" %}

{% block content %}

{% if request.user.is_authenticated and request.user.is_farmer  %}
<!-- 	<div class='row'>
		<div class='col -xs-12'>
			{% if messages %}
			    {% for message in messages %}
			    <p{% if message.tags == "success" %} class="alert alert-success" role="alert"{% endif %}>{{ message }}</p>
			    {% endfor %}
			{% endif %}
		</div>

	</div> -->

	<h1>Add Product</h1>
	    <form method='POST' enctype="multipart/form-data"> {% csrf_token %}
	      <label>Name</label>{{ form.title }}
	      <br>
	      <label>Description</label>{{ form.description }}
	      <br>
	      <label>Price</label>{{ form.price }}
	      <br>
	      <label>Price Unit</label>{{ form.price_unit }}
	      <br>
	      <label>Upload Image</label>{{ form.image }}
	      <br>
	      <label>Available</label>{{ form.availability }}
	      <br>

	      <button type='submit' class='btn btn-default'>Add</button>
	    </form>
{% else %}

{% endif %}

{% endblock %}

products/templates/products/detail.html
{% extends "base.html" %}
<script>
{% block jquery %}


function setPrice(){
    var price = $(".variation_select option:selected").attr("data-price")

    var sale_price = $(".variation_select option:selected").attr("data-sale-price")
    if (sale_price != "" && sale_price != "None" && sale_price != null ) {
    $("#price").html("<h3>" + sale_price + " <small class='og-price'>" + price  + "</small></h3>");
    } else {
    $("#price").html(price);
    }
}
setPrice()

$(".variation_select").change(function(){
    setPrice()
    // var img = $(".variation_select option:selected").attr("data-img")
    // $("img").attr("src", img);

})



// ajax add to cart

$("#submit-btn").click(function(event){
    event.preventDefault();
    var formData = $("#add-form").serialize();
    console.log(formData);
    $.ajax({
        type: "GET", // "POST"
        url: "{% url 'cart:cart' %}",
        data: formData,
        success: function(data) {
            showFlashMessage(data.flash_message);
            updateCartItemCount();
        }, 
        error: function(response, error) {
            // console.log(response)
            // console.log(error)
            $("#add-form").submit()
        }
    })

    // $("#add-form").submit()

})



{% endblock %}
</script>

{% block content %}
<!-- 
    <div class='row'>
        <div class='col -xs-12'>
            {% if messages %}
                {% for message in messages %}
                <p{% if message.tags %} class="alert alert-success" role="alert"{% endif %}>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </div>
    </div> -->
    <div class='row'>
        <div class='col-sm-8'>
                <h1>{{ object.title }}</h1>
                <strong> Last Updated: </strong>{{ object.timestamp|timesince }} ago  <br> <br>          
                <strong> Description:</strong>{{ object.description|linebreaks }}<br> 
                <strong> Price: </strong>{{ object.price}} per {{ object.price_unit }}<br>
                <strong> Quantity = 1 means  </strong>{{ object.price_unit }}<br>
                <strong>Added by:</strong> {{ object.added_by}}<br>
                <strong> Available:</strong>

                {% if object.availability == True %}
                    Yes
                {% else %}
                    No
                {% endif %}

                <br>
                {% if object.image %}
                    <img src='{{ object.image.url }}' class='img-fluid' />
                {% endif %}
                <br>
                <br>
                {% if object.added_by == request.user %}
                    <a href='{{object.get_absolute_url}}edit-product' class="btn btn-primary" role="button">Edit</a>
                    <a href='{{object.get_absolute_url}}delete-product' class="btn btn-danger" role="button">Delete</a>
                {% endif %}
                



        </div>

    
        <div class='col-sm-4'>

                <!-- Product Sidebar -->
                {% if product.availability %}   

                <form id='add-form' method='GET' action="{% url 'cart:cart' %}">
                <p id='jquery-message' class='lead'>

                </p>
                    {% if object.variation_set.count > 1 %}
                    <h3 id='price'>{{ object.variation_set.first.price }}</h3>

                    <select name='item' class='form-control variation_select'>
                        {% for vari_obj in object.variation_set.all %}
                        <!-- <option data-img="http://www.spirit1059.com/pics/Feeds/Articles/2015611/118317/Beach.jpg" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option> -->
                        <option  data-sale-price="{{ vari_obj.sale_price }}" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option>
                        {% endfor %}
                        </select>

                    {% else %}
                        <input type="hidden" name='item' value='{{ object.variation_set.first.id }}' />
                            <h3 id='price'>{% if object.variation_set.first.sale_price %}
                            {{ object.variation_set.first.sale_price  }}
                            <small class='og-price'>{{ object.variation_set.first.price }}</small>
                            {% else %}
                            
                            {{ object.variation_set.first.price }}
                            {% endif %}
                        </h3>


                    {% endif %}
                    <br/>
                    <h3>Quantity: </h3><input class='form-control' type='number' name='qty' value='1' />
                <br/>
                <input id='submit-btn' type='submit' value='Add to Cart' class='btn btn-default' />
                </form>
                {% else %}
                <h3 >Not available</h3>
                {% endif %}

        </div>
    </div>


{% endblock %}
<!-- 
<p>{{ object.user_accessing }}</p>
{% if request.user == object.user_accessing %}
<a href='#' class="btn btn-primary" role="button">Edit</a>
<a href='#' class="btn btn-secondary" role="button">Delete</a>
{% endif %}
 -->

products/templates/products/edit.html
{% extends "base.html" %}

{% block content %}

{% if object.added_by == request.user %}
<!-- 	<div class='row'>
		<div class='col -xs-12'>
			{% if messages %}
			    {% for message in messages %}
			    <p{% if message.tags == "success" %} class="alert alert-success" role="alert"{% endif %}>{{ message }}</p>
			    {% endfor %}
			{% endif %}
		</div>

	</div>
	<div class='row'>
		<div class='col -xs-12'>
			{% if messages %}
			    {% for message in messages %}
			    <p{% if message.tags == "success" %} class="alert alert-success" role="alert"{% endif %}>{{ message }}</p>
			    {% endfor %}
			{% endif %}
		</div>

	</div> -->

	<h1>Edit Product</h1>
	    <form method='POST' enctype="multipart/form-data"> {% csrf_token %}
	      <label>Name</label>{{ form.title }}
	      <br>
	      <label>Description</label>{{ form.description }}
	      <br>
	      <label>Price</label>{{ form.price }}
	      <br>
	      <label>Price Unit</label>{{ form.price_unit }}
	      <br>
	      <label>Upload Image</label>{{ form.image }}
	      <br>
	      <label>Available</label>{{ form.availability }}
	      <br>

	      <button type='submit' class='btn btn-default'>Edit</button>
	    </form>

{% else %}
	<p>You cannot edit,please leave this page</p>

{% endif %}

{% endblock %}

products/templates/products/list.html
{% extends "base.html" %}

{% block content %}
	<div class='row'>
		<div class='col -xs-12'>
			{% if messages %}
			    {% for message in messages %}
			    <p{% if message.tags == "success" %} class="alert alert-success" role="alert"{% endif %}>{{ message }}</p>
			    {% endfor %}
			{% endif %}
		</div>
		<br>	

	</div>
    <div class='row'>
	{% for obj in object_list %}
        <div class='col my-3'>
        {% include 'products/snippets/card.html' with instance=obj %}  
        </div>
    {% endfor %}
	</div>
{% endblock %}

products/templates/products/product_confirm_delete.html
{% extends "base.html" %}



{% block content %}

{% if object.added_by == request.user %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the book with a title "{{ object.title }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
    <a class='btn btn-default' href="{{ object.get_absolute_url }}">Cancel</a>
</form>

{% else %}
	<p>You cannot delete,please leave this page</p>

{% endif %}


{% endblock %}